spring.datasource.url=jdbc:postgresql://localhost:5434/catalogue
spring.datasource.username=postgres
spring.datasource.password=qewr

spring.liquibase.change-log=db/changelog/master-changelog.xml
server.port=9998